### ISSUE TITLE
How to create refresh token?

### ISSUE THREAD

**Issue by Mrkisha** [FriendsOfSymfony/oauth2-php#82]
I've been banging my head around this one for 2 weeks already. Went through code and documentation and still havent managed to find a way how to refresh token after it expires.

Any help on this one?

**Comment by Spomky** [comment]
Refresh token are automatically generated. But depending on the grant type you use, refresh tokens cannot be used (e.g. client credentials and implicit grant type).

**Comment by Mrkisha** [comment]
Ok, so I use client_credentials type. How do I refresh the token after it
expires?

**Comment by Spomky** [comment]
Just create a new one (using the same scope if needed)

**Comment by Mrkisha** [comment]
I guess that's the only solution (that I've tried to avoid if possible for no good reason).

**Comment by Spomky** [comment]
Yes it is the only solution at the moment.
The RFC says that a refresh token should not be issued. The reason is that it is useless to issue a refresh token to get an access token as the client could get another access token directly.

Maybe we could add an option to allow issuance of refresh token with this grant type.
